export const ADD_TRAINING = "ADD_TRAINING";
export const ADD_TRAINING_ERROR = "ADD_TRAINING_ERROR";
export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const ADD_TRAINER = "ADD_TRAINER";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_ERROR = "EDIT_PROFILE_ERROR";
